### ISSUE TITLE
Communication with Neuralm server

### ISSUE THREAD

**Issue by metalglove** [neuralm/Neuralm-Server#81]
Neuralm uses custom message processors and serializers to generically communicate between services.

**TODO**
- [ ] Let user decide which protocol to follow; i.e. which serializer (JSON, YAML, etc) and REST or Websockets
- [ ] Create communication library? Typescript, C#, Java?
- [ ] Create an example project to communicate with the message queue.
  - [ ] Create trainingroom flow
  - [ ] Training with a training session flow
