### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by metalglove** [neuralm/Neuralm-Server#82]
Update the readme to better reflect the current state of the project.

**TODO**
- [ ] Explain manual start up using powershell script
- [ ] Show GIF of training with a training room
- [ ] Show an example of an organism network (if #74 is completed)
- [ ] Refer to an example communication project or wiki (if #81 is completed)
